# Generated by Django 5.1 on 2024-08-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
